"""rename department

Revision ID: 19405e415019
Revises: 17a17a9c1fb9
Create Date: 2026-02-13 14:45:50.627458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19405e415019'
down_revision = '17a17a9c1fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###